package com.matur.lsmestudiantes

class DictSigns {
    companion object{
        var colors = Topic(true, "Colores",
            listOf("Amarillo", "Azul", "Blanco", "Blanco más usado", "Café", "Carne", "Color", "Dorado",
                    "Gris", "Morado", "Naranja", "Negro", "Plateado", "Rojo", "Rojo más usado", "Rosa", "Verde"
            ),
            hashMapOf("Amarillo" to R.raw.colores_amarillo,
                "Azul" to R.raw.colores_azul,
                "Blanco" to R.raw.colores_blanco,
                "Blanco más usado" to R.raw.colores_blanco_habitual,
                "Café" to R.raw.colores_cafe,
                "Carne" to R.raw.colores_carne,
                "Color" to R.raw.colores_color,
                "Dorado" to R.raw.colores_dorado,
                "Gris" to R.raw.colores_gris,
                "Morado" to R.raw.colores_morado,
                "Naranja" to R.raw.colores_naranja,
                "Negro" to R.raw.colores_negro,
                "Plateado" to R.raw.colores_plateado,
                "Rojo" to R.raw.colores_rojo,
                "Rojo más usado" to R.raw.colores_rojo_habitual,
                "Rosa" to R.raw.colores_rosa,
                "Verde"  to R.raw.colores_verde
            ))

        var abecedario = Topic(true, "Abecedario",
            listOf("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "L", "m", "n", "o", "p", "q",
                    "r", "s", "t", "u", "v", "w","x", "y", "z"
            ),
            hashMapOf("a" to R.raw.abc_a,
                "b" to R.raw.abc_b,
                "c" to R.raw.abc_c,
                "d" to R.raw.abc_d,
                "e" to R.raw.abc_e,
                "f" to R.raw.abc_f,
                "g" to R.raw.abc_g,
                "h" to R.raw.abc_h,
                "i" to R.raw.abc_i,
                "j" to R.raw.abc_j,
                "k" to R.raw.abc_k,
                "L" to R.raw.abc_l,
                "m" to R.raw.abc_m,
                "n" to R.raw.abc_n,
                "o" to R.raw.abc_o,
                "p" to R.raw.abc_p,
                "q" to R.raw.abc_q,
                "r" to R.raw.abc_r,
                "s" to R.raw.abc_s,
                "t" to R.raw.abc_t,
                "u" to R.raw.abc_u,
                "v" to R.raw.abc_v,
                "w" to R.raw.abc_w,
                "x" to R.raw.abc_x,
                "y" to R.raw.abc_y,
                "z" to R.raw.abc_z
            ))

        var numeros = Topic(true, "Números",
            listOf("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13",
                    "14", "15 más usado", "15", "16", "17", "18", "19", "20", "30","30 más usado", "40",
                    "50", "60", "70", "80", "90", "100", "1000", "2000", "1000000"
            ),
            hashMapOf("1" to R.raw.numeros_1,
                "2" to R.raw.numeros_2,
                "3" to R.raw.numeros_3,
                "4" to R.raw.numeros_4,
                "5" to R.raw.numeros_5,
                "6" to R.raw.numeros_6,
                "7" to R.raw.numeros_7,
                "8" to R.raw.numeros_8,
                "9" to R.raw.numeros_9,
                "10" to R.raw.numeros_10,
                "11" to R.raw.numeros_11,
                "12" to R.raw.numeros_12,
                "13" to R.raw.numeros_13,
                "14" to R.raw.numeros_14,
                "15 más usado" to R.raw.numeros_15_habitual,
                "15" to R.raw.numeros_15,
                "16" to R.raw.numeros_16,
                "17" to R.raw.numeros_17,
                "18" to R.raw.numeros_18,
                "19" to R.raw.numeros_19,
                "20" to R.raw.numeros_20,
                "30" to R.raw.numeros_30,
                "30 más usado" to R.raw.numeros_30_habitual,
                "40" to R.raw.numeros_40,
                "50" to R.raw.numeros_50_2,
                "60" to R.raw.numeros_60,
                "70" to R.raw.numeros_70,
                "80" to R.raw.numeros_80,
                "90" to R.raw.numeros_90,
                "100" to R.raw.numeros_100,
                "1000" to R.raw.numeros_1000,
                "2000" to R.raw.numeros_2000,
                "1000000" to R.raw.numeros_1000000
            ))

        var saludos = Topic(true, "Saludos",
            listOf("Adios", "Bien", "Buenas noches", "Buenas tardes", "Buenos días",
            "¿Cómo estas?", "¿Cómo te llamas?", "Cuidate", "De nada", "Excelente",
            "Gracias", "Hasta mañana", "Hasta pronto", "Hola", "Igualmente", "Mal", "Más o menos",
            "Mucho gusto", "Nos vemos", "Por favor"
            ),

            hashMapOf("Adios" to R.raw.saludos_adios,
                "Bien" to R.raw.saludos_bien,
                "Buenas noches" to R.raw.saludos_buenas_noches,
                "Buenas tardes" to R.raw.saludos_buenas_tardes,
                "Buenos días" to R.raw.saludos_buenos_dias,
                "¿Cómo estas?" to R.raw.saludos_como_estas,
                "¿Cómo te llamas?" to R.raw.saludos_como_te_llamas,
                "Cuidate" to R.raw.saludos_cuidate,
                "De nada" to R.raw.saludos_denada,
                "Excelente" to R.raw.saludos_excelente,
                "Gracias" to R.raw.saludos_gracias,
                "Hasta mañana" to R.raw.saludos_hasta_manana,
                "Hasta pronto" to R.raw.saludos_hasta_pronto,
                "Hola" to R.raw.saludos_hola,
                "Igualmente" to R.raw.saludos_igualmente,
                "Mal" to R.raw.saludos_mal,
                "Más o menos" to R.raw.saludos_mas_menos,
                "Mucho gusto" to R.raw.saludos_mucho_gusto,
                "Nos vemos" to R.raw.saludos_nosvemos,
                "Por favor" to R.raw.saludos_porfavor
                ))

        var diasMeses = Topic(true, "Días y meses",
            listOf("Abril", "Agosto", "Día", "Diciembre","Domingo", "Enero", "Febrero", "Jueves","Julio",
                    "Junio", "Lunes", "Martes", "Marzo", "Mayo", "Mes", "Miércoles", "Miércoles (más usado)",
                    "Noviembre", "Octubre", "Sábado", "Semana", "Septiembre"
                ),
            hashMapOf("Abril" to R.raw.dias_meses_abril,
                "Agosto" to R.raw.dias_meses_agosto,
                "Día" to R.raw.dias_meses_dia,
                "Diciembre" to R.raw.dias_meses_diciembre,
                "Domingo" to R.raw.dias_meses_domingo,
                "Enero" to R.raw.dias_meses_enero,
                "Febrero" to R.raw.dias_meses_febrero,
                "Jueves" to R.raw.dias_meses_jueves,
                "Julio" to R.raw.dias_meses_julio,
                "Junio" to R.raw.dias_meses_junio,
                "Lunes" to R.raw.dias_meses_lunes,
                "Martes" to R.raw.dias_meses_martes,
                "Marzo" to R.raw.dias_meses_marzo,
                "Mayo" to R.raw.dias_meses_mayo,
                "Mes" to R.raw.dias_meses_mes,
                "Miércoles" to R.raw.dias_meses_miercoles,
                "Miércoles (más usado)" to R.raw.dias_meses_miercoles_habitual,
                "Noviembre" to R.raw.dias_meses_noviembre,
                "Octubre" to R.raw.dias_meses_octubre,
                "Sábado" to R.raw.dias_meses_sabado,
                "Semana" to R.raw.dias_meses_semana,
                "Septiembre" to R.raw.dias_meses_septiembre
            ))

        var alimentos = Topic(true, "Alimentos",
            listOf("Aceite", "Alimentos","Arroz", "Azúcar", "Carne", "Chilaquiles", "Enchiladas", "Frijol",
                    "Fruta", "Huevo", "Leche", "Pizza 1", "Pizza 2", "Pizza 3", "Pollo", "Pozole",
                    "Puerco", "Quesadilla", "Res", "Sal", "Salsa", "Sopa", "Spaghetti 1", "Spaghetti 2", "Spaghetti 3",
                    "Sushi", "Taco", "Tamal", "Tortillas", "Verdura"
            ),
            hashMapOf("Aceite" to R.raw.alimentos_aceite,
                "Alimentos" to R.raw.alimentos_alimento,
                "Arroz" to R.raw.alimentos_arroz,
                "Azúcar" to R.raw.alimentos_azucar,
                "Carne" to R.raw.alimentos_carne,
                "Chilaquiles" to R.raw.alimentos_chilaquiles,
                "Enchiladas" to R.raw.alimentos_enchiladas,
                "Frijol" to R.raw.alimentos_frijol,
                "Fruta" to R.raw.alimentos_fruta,
                "Huevo" to R.raw.alimentos_huevo,
                "Leche" to R.raw.alimentos_leche,
                "Pizza 1" to R.raw.alimentos_pizza1,
                "Pizza 2" to R.raw.alimentos_pizza2,
                "Pizza 3" to R.raw.alimentos_pizza3,
                "Pollo" to R.raw.alimentos_pollo,
                "Pozole" to R.raw.alimentos_pozole,
                "Puerco" to R.raw.alimentos_puerco,
                "Quesadilla" to R.raw.alimentos_quesadilla,
                "Res" to R.raw.alimentos_res,
                "Sal" to R.raw.alimentos_sal,
                "Salsa" to R.raw.alimentos_salsa,
                "Sopa" to R.raw.alimentos_sopa,
                "Spaghetti 1" to R.raw.alimentos_spagatti1,
                "Spaghetti 2" to R.raw.alimentos_spaggeti2,
                "Spaghetti 3" to R.raw.alimentos_spaggeti3,
                "Sushi" to R.raw.alimentos_sushi,
                "Taco" to R.raw.alimentos_taco,
                "Tamal" to R.raw.alimentos_tamal,
                "Tortillas" to R.raw.alimentos_tortillas,
                "Verdura" to R.raw.alimentos_verdura
            ))

        var familia = Topic(true, "Familia",
            listOf("Abuelo", "Amante", "Amigo", "Cuñado", "Esposo", "Familia", "Femenino", "Hermano",
                    "Hijo", "Mamá", "Nieto opc. 1", "Nieto opc. 2", "Novio", "Nuera", "Papá",
                    "Primo", "Prometido", "Sobrino", "Tío opc. 1", "Tío opc. 2", "Yerno"
                ),
            hashMapOf("Abuelo" to R.raw.familia_abuelo,
                "Amante" to R.raw.familia_amante,
                "Amigo" to R.raw.familia_amigo,
                "Cuñado" to R.raw.familia_cunado,
                "Esposo" to R.raw.familia_esposo,
                "Familia" to R.raw.familia_familia,
                "Femenino" to R.raw.familia_femenino,
                "Hermano" to R.raw.familia_hermano,
                "Hijo" to R.raw.familia_hijo,
                "Mamá" to R.raw.familia_mama,
                "Nieto opc. 1" to R.raw.familia_nietos1,
                "Nieto opc. 2" to R.raw.familia_nietos2,
                "Novio" to R.raw.familia_novio,
                "Nuera" to R.raw.familia_nuera,
                "Papá" to R.raw.familia_papa,
                "Primo" to R.raw.familia_primo,
                "Prometido" to R.raw.familia_prometido,
                "Sobrino" to R.raw.familia_sobrino,
                "Tío opc. 1" to R.raw.familia_tios1,
                "Tío opc. 2" to R.raw.familia_tios2,
                "Yerno" to R.raw.familia_yerno
            ))

        var emociones = Topic(true, "Emociones",
            listOf("Aburrido", "Agotado", "Alegre", "Apenado", "Celoso", "Enamorado", "Enojado",
                    "Feliz", "Preocupado", "Sorprendido", "Tranquilo", "Triste"
                ),
            hashMapOf("Aburrido" to R.raw.emociones_aburrido,
                "Agotado" to R.raw.emociones_agotado,
                "Alegre" to R.raw.emociones_alegre,
                "Apenado" to R.raw.emociones_apenado,
                "Celoso" to R.raw.emociones_celoso,
                "Enamorado" to R.raw.emociones_enamorado,
                "Enojado" to R.raw.emociones_enojado,
                "Feliz" to R.raw.emociones_feliz,
                "Preocupado" to R.raw.emociones_preocupado,
                "Sorprendido" to R.raw.emociones_sorprendido,
                "Tranquilo" to R.raw.emociones_tranquilo,
                "Triste" to R.raw.emociones_triste
            ))


        var animales = Topic(true, "Animales",
            listOf("Abeja", "Águila", "Alacran", "Animales", "Araña", "Ballena", "Borrego", "Buho",
                    "Burro", "Caballo", "Camaron", "Caracol", "Cebra", "Cerdo", "Chango", "Cisne", "Cocodrilo",
                    "Conejo", "Delfin", "Elefante", "Elefante (trompa)", "Foca", "Gallina", "Gallo",
                    "Gato (1 dedo)", "Gato (3 dedos)", "Gorila", "Iguana", "Jirafa", "Lagarto", "León",
                    "Mapache", "Mariposa", "Oso", "Pajaro/ave", "Perro", "Pez", "Pingüino", "Pollo","Sapo",
                    "Tiburon 1", "Tiburon 2", "Tiburon 3", "Tigre", "Toro", "Vaca", "Venado", "Vibora",
                    "Zorrillo 1", "Zorrillo 2"
            ),
            hashMapOf("Abeja" to R.raw.animales_abeja,
                "Águila" to R.raw.animales_aguila,
                "Alacran" to R.raw.animales_alacran,
                "Animales" to R.raw.animales_animales,
                "Araña" to R.raw.animales_arania,
                "Ballena" to R.raw.animales_ballena,
                "Borrego" to R.raw.animales_borrego,
                "Buho" to R.raw.animales_buho,
                "Burro" to R.raw.animales_burro,
                "Caballo" to R.raw.animales_caballo,
                "Camaron" to R.raw.animales_camaron,
                "Caracol" to R.raw.animales_caracol,
                "Cebra" to R.raw.animales_cebra,
                "Cerdo" to R.raw.animales_cerdo,
                "Chango" to R.raw.animales_chango,
                "Cisne" to R.raw.animales_cisne,
                "Cocodrilo" to R.raw.animales_cocodrilo,
                "Conejo" to R.raw.animales_conejo,
                "Delfin" to R.raw.animales_delfin,
                "Elefante" to R.raw.animales_elefante,
                "Elefante (trompa)" to R.raw.animales_elefante_trompa,
                "Foca" to R.raw.animales_foca,
                "Gallina" to R.raw.animales_gallina,
                "Gallo" to R.raw.animales_gallo,
                "Gato (1 dedo)" to R.raw.animales_gato_1dedo,
                "Gato (3 dedos)" to R.raw.animales_gato_3dedos,
                "Gorila" to R.raw.animales_gorila,
                "Iguana" to R.raw.animales_iguana,
                "Jirafa" to R.raw.animales_jirafa,
                "Lagarto" to R.raw.animales_lagarto,
                "León" to R.raw.animales_leon,
                "Mapache" to R.raw.animales_mapache,
                "Mariposa" to R.raw.animales_mariposa,
                "Oso" to R.raw.animales_oso,
                "Pajaro/ave" to R.raw.animales_pajaro_ave,
                "Perro" to R.raw.animales_perro,
                "Pez" to R.raw.animales_pez,
                "Pingüino" to R.raw.animales_pinguino,
                "Pollo" to R.raw.animales_pollo,
                "Sapo" to R.raw.animales_sapo,
                "Tiburon 1" to R.raw.animales_tiburon1,
                "Tiburon 2" to R.raw.animales_tiburon2,
                "Tiburon 3" to R.raw.animales_tiburon3,
                "Tigre" to R.raw.animales_tigre,
                "Toro" to R.raw.animales_toro,
                "Vaca" to R.raw.animales_vaca,
                "Venado" to R.raw.animales_venado,
                "Vibora" to R.raw.animales_vibora,
                "Zorrillo 1" to R.raw.animales_zorrillo1,
                "Zorrillo 2" to R.raw.animales_zorrillo2
            ))

        var adjetivos = Topic(true, "Adjetivos claificativos",
            listOf("Adjetivos claificativos", "Alto", "Amable", "Barato", "Blando", "Cariñoso", "Caro",
                "Chaparro", "Corto", "Débil", "Duro", "Educado", "Egoíst", "Enfermo", "Fuerte", "Grande opción 1",
                "Grande opción 2", "Honrado", "Largo", "Lento", "Malo", "Nuevo o amanecer", "Penoso",
                "Pequeño opcion 1", "Pequeño opcion 2", "Débil", "Pobre", "Rápido", "Rico", "Sano", "Viejo"
            ),
            hashMapOf("Adjetivos claificativos" to R.raw.adj_adejetivos_calificativos,
                "Alto" to R.raw.adj_alto,
                "Amable" to R.raw.adj_amable,
                "Barato" to R.raw.adj_barato,
                "Blando" to R.raw.adj_blando,
                "Cariñoso" to R.raw.adj_carinioso,
                "Caro" to R.raw.adj_caro,
                "Chaparro" to R.raw.adj_chaparro,
                "Corto" to R.raw.adj_corto,
                "Débil" to R.raw.adj_debil,
                "Duro" to R.raw.adj_duro,
                "Educado" to R.raw.adj_educado,
                "Egoíst" to R.raw.adj_egoista,
                "Enfermo" to R.raw.adj_enfermo,
                "Fuerte" to R.raw.adj_fuerte,
                "Grande opción 1" to R.raw.adj_grande_1,
                "Grande opción 2" to R.raw.adj_grande_2,
                "Honrado" to R.raw.adj_honrado,
                "Largo" to R.raw.adj_largo,
                "Lento" to R.raw.adj_lento,
                "Malo" to R.raw.adj_malo,
                "Nuevo o amanecer" to R.raw.adj_nuevo_amanecer,
                "Penoso" to R.raw.adj_penoso,
                "Pequeño opcion 1" to R.raw.adj_pequenio_1,
                "Pequeño opcion 2" to R.raw.adj_pequenio_2,
                "Débil" to R.raw.adj_debil,
                "Pobre" to R.raw.adj_pobre,
                "Rápido" to R.raw.adj_rapido,
                "Rico" to R.raw.adj_rico,
                "Sano" to R.raw.adj_sano,
                "Viejo" to R.raw.adj_viejo
            ))

        var amor_amistad = Topic(true, "Amor y amistad",
            listOf("Amor y amistad", "Abrazo", "Amigo", "Amistad", "Amor", "Beso", "Besos",
                "Bombón", "Carta", "Cena", "Chocolate", "Cita", "Compromiso", "Dulce", "Esposo", "Flores",
                "I love you", "Juntos", "Me gustas", "Novio", "Oso de peluche 1", "Oso de peluche 2", "Paleta",
                "Prometido", "Ramo de flores", "Regalo", "Tarjeta de regalo", "Te amo"
            ),
            hashMapOf("Abrazo" to R.raw.amor_abrazo,
                "Amigo" to R.raw.amor_amigo,
                "Amistad" to R.raw.amor_amistad,
                "Amor" to R.raw.amor_amor,
                "Beso" to R.raw.amor_beso,
                "Besos" to R.raw.amor_besos,
                "Bombón" to R.raw.amor_bombon,
                "Carta" to R.raw.amor_carta,
                "Cena" to R.raw.amor_cena,
                "Chocolate" to R.raw.amor_chocolate,
                "Cita" to R.raw.amor_cita,
                "Compromiso" to R.raw.amor_compromiso,
                "Dulce" to R.raw.amor_dulce,
                "Esposo" to R.raw.amor_esposo,
                "Flores" to R.raw.amor_flores,
                "I love you" to R.raw.amor_i_love_you,
                "Juntos" to R.raw.amor_juntos,
                "Me gustas" to R.raw.amor_me_gustas,
                "Novio" to R.raw.amor_novio,
                "Oso de peluche 1" to R.raw.amor_oso_peluche_1,
                "Oso de peluche 2" to R.raw.amor_oso_peluche_2,
                "Paleta" to R.raw.amor_paleta,
                "Prometido" to R.raw.amor_prometido,
                "Ramo de flores" to R.raw.amor_ramo_flores,
                "Regalo" to R.raw.amor_regalo,
                "Tarjeta de regalo" to R.raw.amor_tarjeta_regalo,
                "Te amo" to R.raw.amor_te_amo
            ))

        var capitales = Topic(true, "Capitales",
            listOf("CDMX", "Chetumal", "Chilpancingo", "Ciudad Victoria 1", "Ciudad Victoria 2", "Cuernavaca", "Culiacan 1",
                "Culiacan 2", "Guadalajara", "Hermosillo", "La paz", "Mérida", "Mexicali", "Moterrey", "Morelia",
                "Pachuca", "Saltillo", "Tepic", "Toluca", "Tuxla Gutierrez", "Villa hermosa", "Xalapa"
            ),
            hashMapOf("CDMX" to R.raw.capi_cdmx,
                "Chetumal" to R.raw.capi_chetumal,
                "Chilpancingo" to R.raw.capi_chilpancingo,
                "Ciudad Victoria 1" to R.raw.capi_ciudad_victoria_1,
                "Ciudad Victoria 2" to R.raw.capi_ciudad_victoria_2,
                "Cuernavaca" to R.raw.capi_cuernavaca,
                "Culiacan 1" to R.raw.capi_culiacan_1,
                "Culiacan 2" to R.raw.capi_culiacan_2,
                "Guadalajara" to R.raw.capi_guadalajara,
                "Hermosillo" to R.raw.capi_hermosillo,
                "La paz" to R.raw.capi_la_paz,
                "Mérida" to R.raw.capi_merida,
                "Mexicali" to R.raw.capi_mexicali,
                "Moterrey" to R.raw.capi_monterrey,
                "Morelia" to R.raw.capi_morelia,
                "Pachuca" to R.raw.capi_pachuca,
                "Saltillo" to R.raw.capi_saltillo,
                "Tepic" to R.raw.capi_tepic,
                "Toluca" to R.raw.capi_toluca,
                "Tuxla Gutierrez" to R.raw.capi_tuxcla_gutuerres,
                "Villa hermosa" to R.raw.capi_villa_hermosa,
                "Xalapa" to R.raw.capi_xalapa
            ))

        var estados = Topic(true, "Estados",
            listOf("Aguascalientes", "Baja California Norte", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Ciudad",
                "Ciudad de México", "Coahuila", "Colima", "Durando", "Estado 1", "Estado 2", "Estado de México", "Guanajuato", "Guerreo 1",
                "Guerreo 2", "Hidalgo", "Jalisco", "Michoacan", "Morelos", "Nayarit", "Nuevo León",
                "Oaxaca", "Puebla", "Queretaro", "Quitana Roo", "San Luis Potosi", "Sinaloa 1", "Sinaloa 2", "Sonora",
                "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatan", "Zacatecas"

            ),
            hashMapOf("Aguascalientes" to R.raw.edo_aguascalientes,
                "Baja California Norte" to R.raw.edo_baja_california_norte,
                "Baja California Sur" to R.raw.edo_baja_california_sur,
                "Campeche" to R.raw.edo_campeche,
                "Chiapas" to R.raw.edo_chiapas,
                "Chihuahua" to R.raw.edo_chihuahua,
                "Ciudad" to R.raw.edo_ciudad,
                "Ciudad de México"  to R.raw.edo_ciudad_mexico,
                "Coahuila" to R.raw.edo_coahuila,
                "Colima" to R.raw.edo_colima,
                "Durando" to R.raw.edo_durango,
                "Estado 1" to R.raw.edo_estado,
                "Estado 2" to R.raw.edo_estado_2,
                "Estado de México" to R.raw.edo_estado_mexico,
                "Guanajuato" to R.raw.edo_guanajuato,
                "Guerreo 1" to R.raw.edo_guerrero_1,
                "Guerreo 2" to R.raw.edo_guerrero_2,
                "Hidalgo" to R.raw.edo_hidalgo,
                "Jalisco" to R.raw.edo_jalisco,
                "Michoacan" to R.raw.edo_michoacan,
                "Morelos" to R.raw.edo_morelos,
                "Nayarit" to R.raw.edo_nayarit,
                "Nuevo León" to R.raw.edo_nuevo_leon,
                "Oaxaca" to R.raw.edo_oaxaca,
                "Puebla" to R.raw.edo_puebla,
                "Queretaro" to R.raw.edo_queretaro,
                "Quitana Roo" to R.raw.edo_quintana_roo,
                "San Luis Potosi" to R.raw.edo_san_luis_potosi,
                "Sinaloa 1" to R.raw.edo_sinaloa_1,
                "Sinaloa 2" to R.raw.edo_sinaloa_2,
                "Sonora" to R.raw.edo_sonora,
                "Tabasco" to R.raw.edo_tabasco,
                "Tamaulipas" to R.raw.edo_tamaulipas,
                "Tlaxcala" to R.raw.edo_tlaxcala,
                "Veracruz" to R.raw.edo_veracruz,
                "Yucatan" to R.raw.edo_yucatan,
                "Zacatecas" to R.raw.edo_zacatecas
            ))

        var indicaciones = Topic(true, "Indicaciones",
            listOf("A la derecha", "A la izquierda", "Abajo", "Abajo 2", "Afuera 1", "Afuera 2", "Ante o frente",
                "Arriba 1", "Arriba 2", "Cuadra", "Cuadras", "Debajo", "Derecha", "Desde", "Entre", "Esquina",
                "Izquierda", "Lado", "Lejos", "Con", "Según"
            ),
            hashMapOf("A la derecha" to R.raw.indicaciones_a_la_derecha,
                "A la izquierda" to R.raw.indicaciones_a_la_izquierda,
                "Abajo" to R.raw.indicaciones_abajo,
                "Abajo 2" to R.raw.indicaciones_abajo_2,
                "Afuera 1" to R.raw.indicaciones_afuera_1,
                "Afuera 2" to R.raw.indicaciones_afuera_2,
                "Ante o frente" to R.raw.indicaciones_ante_frente,
                "Arriba 1" to R.raw.indicaciones_arriba_1,
                "Arriba 2" to R.raw.indicaciones_arriba_2,
                "Cuadra" to R.raw.indicaciones_cuadra,
                "Cuadras" to R.raw.indicaciones_cuadras,
                "Debajo" to R.raw.indicaciones_debajo,
                "Derecha" to R.raw.indicaciones_derecha,
                "Desde" to R.raw.indicaciones_desde,
                "Entre" to R.raw.indicaciones_entre,
                "Esquina" to R.raw.indicaciones_esquina,
                "Izquierda" to R.raw.indicaciones_izquierda,
                "Lado" to R.raw.indicaciones_lado,
                "Lejos" to R.raw.indicaciones_lejos,
                "Con" to R.raw.indicaciones_pronombre_con,
                "Según" to R.raw.indicaciones_segun
            ))

        var lugares = Topic(true, "Lugares",
            listOf("Aereopuerto", "Aereopuerto o aterrizar", "Banco", "Cafetería", "Casa", "Cine", "Circo",
                "Edificio", "Estadio", "Fabrica", "Farmacia", "Feria", "Gasolinera", "Hospital", "Hotel",
                "Iglesia", "Lugar", "Oxxo 1", "Oxxo 2", "Parque", "Pizzeria", "Restaurante 1", "Restaurante 2",
                "Súper Mercado", "Tienda"
            ),
            hashMapOf("Aereopuerto" to R.raw.lugares_aereopuerto,
                "Aereopuerto o aterrizar" to R.raw.lugares_aereopuerto_aterrizar,
                "Banco" to R.raw.lugares_banco,
                "Cafetería" to R.raw.lugares_cafeteria,
                "Casa" to R.raw.lugares_casa,
                "Cine" to R.raw.lugares_cine,
                "Circo" to R.raw.lugares_circo,
                "Edificio" to R.raw.lugares_edificio,
                "Estadio" to R.raw.lugares_estadio,
                "Fabrica" to R.raw.lugares_fabrica,
                "Farmacia" to R.raw.lugares_farmacia,
                "Feria" to R.raw.lugares_feria,
                "Gasolinera" to R.raw.lugares_gasolineria,
                "Hospital" to R.raw.lugares_hospital,
                "Hotel" to R.raw.lugares_hotel,
                "Iglesia" to R.raw.lugares_iglesia,
                "Lugar" to R.raw.lugares_lugar,
                "Oxxo 1" to R.raw.lugares_oxxo_1,
                "Oxxo 2" to R.raw.lugares_oxxo_2,
                "Parque" to R.raw.lugares_parque,
                "Pizzeria" to R.raw.lugares_pizzeria,
                "Restaurante 1" to R.raw.lugares_restaurante_1,
                "Restaurante 2" to R.raw.lugares_restaurante_2,
                "Súper Mercado" to R.raw.lugares_supermercado,
                "Tienda" to R.raw.lugares_tienda
            ))

        var preguntas = Topic(true, "Preguntas",
            listOf("¿Cómo?", "¿Cuál?", "¿Cuándo? Opción 1", "¿Cuándo? Opción 2", "¿Cuánto? (costo)", "¿Cuánto cuesta?", "¿Cuánto vale?",
                "¿Cuántos? (plural)", "¿Dónde?", "¿Para qué?", "¿Por qué?", "Preguntas", "¿Qué?", "¿Qué paso?", "¿Qué piensas?",
                "¿Qué haces?/Hacer", "¿Quién? (Opción 1)", "¿Quién? (Opción 2)", "¿Quiénes?"
            ),
            hashMapOf("¿Cómo?" to R.raw.preguntas_como,
                "¿Cuál?" to R.raw.preguntas_cual,
                "¿Cuándo? Opción 1" to R.raw.preguntas_cuando_1,
                "¿Cuándo? Opción 2" to R.raw.preguntas_cuando_2,
                "¿Cuánto? (costo)" to R.raw.preguntas_cuanto_costo,
                "¿Cuánto cuesta?" to R.raw.preguntas_cuanto_cuesta,
                "¿Cuánto vale?" to R.raw.preguntas_cuanto_vale,
                "¿Cuántos? (plural)" to R.raw.preguntas_cuantos_plural,
                "¿Dónde?" to R.raw.preguntas_donde,
                "¿Para qué?" to R.raw.preguntas_para_que,
                "¿Por qué?" to R.raw.preguntas_por_que,
                "Preguntas" to R.raw.preguntas_preguntas,
                "¿Qué?" to R.raw.preguntas_que,
                "¿Qué paso?" to R.raw.preguntas_que_paso,
                "¿Qué piensas?" to R.raw.preguntas_que_piensas,
                "¿Qué haces?/Hacer" to R.raw.preguntas_quehaces_hacer,
                "¿Quién? (Opción 1)" to R.raw.preguntas_quien_1,
                "¿Quién? (Opción 2)" to R.raw.preguntas_quien_2,
                "¿Quiénes?" to R.raw.preguntas_quienes
            ))

        var pronombres = Topic(true, "Pronombres",
            listOf("Él", "Ellos", "Mío", "Nosotros 1", "Nosotros 2", "Nuestro 1", "Nuestro 2",
                "Pronombres", "Suyo", "Suyo (de ustedes)", "Tu", "Tuyo", "Ustedes", "Yo"
            ),
            hashMapOf("Él" to R.raw.pronombres_el,
                "Ellos" to R.raw.pronombres_ellos,
                "Mío" to R.raw.pronombres_mio,
                "Nosotros 1" to R.raw.pronombres_nosotros,
                "Nosotros 2" to R.raw.pronombres_nosotros_2,
                "Nuestro 1" to R.raw.pronombres_nuestro_1,
                "Nuestro 2" to R.raw.pronombres_nuestro_2,
                "Pronombres" to R.raw.pronombres_pronombres,
                "Suyo" to R.raw.pronombres_suyo,
                "Suyo (de ustedes)" to R.raw.pronombres_suyo_de_ustedes,
                "Tu" to R.raw.pronombres_tu,
                "Tuyo" to R.raw.pronombres_tuyo,
                "Ustedes" to R.raw.pronombres_ustedes,
                "Yo" to R.raw.pronombres_yo
            ))

        var verbos = Topic(true, "Verbos",
            listOf("Amar", "Comer", "Conocer", "Contar", "Dar", "Deber", "Decir",
                "Descansar", "Dolor", "Dormir", "Entender", "Entrar", "Explicar", "Gustar", "Hablar",
                "Ir", "Llegar", "Morir", "Nacer", "Pensar", "Querer", "Salir", "Sentir",
                "Venir", "Ver", "Verbos", "Vivir"
            ),
            hashMapOf("Amar" to R.raw.verbos_amar,
                "Comer" to R.raw.verbos_comer,
                "Conocer" to R.raw.verbos_conocer_corregir,
                "Contar" to R.raw.verbos_contar,
                "Dar" to R.raw.verbos_dar,
                "Deber" to R.raw.verbos_deber,
                "Decir" to R.raw.verbos_decir,
                "Descansar" to R.raw.verbos_descansar,
                "Dolor" to R.raw.verbos_dolor,
                "Dormir" to R.raw.verbos_dormir,
                "Entender" to R.raw.verbos_entender,
                "Entrar" to R.raw.verbos_entrar,
                "Explicar" to R.raw.verbos_explicar,
                "Gustar" to R.raw.verbos_gustar,
                "Hablar" to R.raw.verbos_hablar,
                "Ir" to R.raw.verbos_ir,
                "Llegar" to R.raw.verbos_llegar,
                "Morir" to R.raw.verbos_morir,
                "Nacer" to R.raw.verbos_nacer,
                "Pensar" to R.raw.verbos_pensar,
                "Querer" to R.raw.verbos_querer,
                "Salir" to R.raw.verbos_salir,
                "Sentir" to R.raw.verbos_sentir,
                "Venir" to R.raw.verbos_venir,
                "Ver" to R.raw.verbos_ver,
                "Verbos" to R.raw.verbos_verbos,
                "Vivir" to R.raw.verbos_vivir
            ))
        var dict = hashMapOf("Saludos" to saludos, "Abecedario" to abecedario, "Días y meses" to diasMeses,
                            "Números" to numeros, "Colores" to colors, "Alimentos" to alimentos, "Familia" to familia,
                            "Emociones" to emociones, "Animales" to animales, "Adjetivos claificativos" to adjetivos,
                            "Amor y amistad" to amor_amistad, "Capitales" to capitales, "Estados" to estados,
                            "Indicaciones" to indicaciones, "Lugares" to lugares, "Preguntas" to preguntas,
                            "Pronombres" to pronombres, "Verbos" to verbos)

        fun getAllTopics():MutableList<Topic>{
            val topics: MutableList<Topic> = mutableListOf()
            for (key in dict.keys){
                topics.add(dict[key]!!)
            }

            return topics
        }

        fun getSpecificTopics(topicsSelected: List<String>): MutableList<Topic>{
            val topics: MutableList<Topic> = mutableListOf()
            for (key in topicsSelected){
                topics.add(dict[key]!!)
            }
            return topics
        }
        fun getSpecificTopic(topicSelected: String): Topic{
            return dict[topicSelected]!!
        }

        fun getSelectedTopics(): MutableList<Topic>{
            val topics: MutableList<Topic> = mutableListOf()
            for (key in dict.keys){
                if(dict[key]!!.use){
                    topics.add(dict[key]!!)
                }
            }

            return topics
        }
    }
}